### ISSUE TITLE
BLS Tool: Build for Linux (Ubuntu 20.x+ x86, Ubuntu 20.x+ ARM64)

### ISSUE THREAD

**Issue by wmerfalen** [dashhive/bls#2]

**Comment by coolaj86** [comment]
This shouldn't really be "Ubuntu" specific. It should work on anything that follows LSB. Or am I mistaken?

I believe there was a recent LSB breaking change to `libc`, though I'm not sure if it was in 20.x or 22.x. In any case, since we're not going to gain traction with old releases, let's just focus on the current LSB / libc and MUSL, not old versions.

The release needs to be `unknown-linux-gnu` (current LSB) or `uknown-linux-musl` (all linuxes), not Ubuntu x.y, etc.

I've got another issue open for using the standard host triple rather than flavored and subversioned OS names.

Closing this as complete.

Excellent work!
